# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usbhid" "uas" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/encrypted";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."encrypted".device = "/dev/disk/by-uuid/7fd1ced6-81d7-4b7a-8486-ebef140cafcb";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/72F5-08ED";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" "nofail" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
