# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "uas" ];
  boot.initrd.kernelModules = [
    "vfat"
    "nls_cp437"
    "nls_iso8859-1"
    "usbhid"
  ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  hardware.asahi.peripheralFirmwareDirectory = ../../support/firmware;
  hardware.uinput.enable = true;

  fileSystems."/" = {
    device = "/dev/mapper/encrypted";
    fsType = "ext4";
  };

  boot.initrd.luks = {
    yubikeySupport = true;
    devices."encrypted" = {
      device = "/dev/disk/by-uuid/693adac2-411f-4959-a35b-537bc77d7b8a";
      yubikey = {
        slot = 2;
        twoFactor = true; # Set to false for 1FA
        gracePeriod = 30; # Time in seconds to wait for Yubikey to be inserted
        keyLength = 64; # Set to $KEY_LENGTH/8
        saltLength = 64; # Set to $SALT_LENGTH

        storage = {
          device = "/dev/disk/by-uuid/7860-190D"; # Be sure to update this to the correct volume
          fsType = "vfat";
          path = "/crypt-storage/default";
        };
      };
    };
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7860-190D";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
